{application,cluster,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{cluster_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[cluster,cluster_app,cluster_lib,cluster_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
